### ISSUE TITLE
AI-Benchmark doesn't run correctly (instead of Tensorflow 1.15 DirectML which yes)..

### ISSUE THREAD

**Issue by oscarbg** [microsoft/tensorflow-directml-plugin#218]
Hi,
trying to run ai-benchmark on a system with:
RX Vega latest driver
Win 11 insider version

note old Tensorflow 1.15 DirectML works..

installed with on a clean Python 3.10.2 env:
pip install tensorflow-cpu==2.9.1
pip install tensorflow-directml-plugin
pip install ai-benchmark

seems main fail is:
tensorflow.python.framework.errors_impl.InvalidArgumentError: AssignRefVariable is not yet supported for pluggable devices in this version of TensorFlow.

log:
```
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2022-06-23 20:53:42.774835: I tensorflow/c/logging.cc:34] Successfully opened dynamic library c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow-plugins/directml/directml.0de2b4431c6572ee74152a7ee0cd3fb1534e4a95.dll
2022-06-23 20:53:42.775767: I tensorflow/c/logging.cc:34] Successfully opened dynamic library dxgi.dll
2022-06-23 20:53:42.780394: I tensorflow/c/logging.cc:34] Successfully opened dynamic library d3d12.dll
2022-06-23 20:53:43.066846: I tensorflow/c/logging.cc:34] DirectML device enumeration: found 1 compatible adapters.
>>>
>>> tf.config.experimental.list_physical_devices('GPU')
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
>>> print(tf.__version__)
2.9.1
>>> from ai_benchmark import AIBenchmark
>>> results = AIBenchmark().run()

>>   AI-Benchmark-v.0.1.2
>>   Let the AI Games begin..

2022-06-23 20:55:17.167099: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-23 20:55:17.167680: I tensorflow/c/logging.cc:34] DirectML: creating device on adapter 0 (Radeon RX Vega)
2022-06-23 20:55:17.287625: I tensorflow/c/logging.cc:34] Successfully opened dynamic library Kernel32.dll
2022-06-23 20:55:17.289964: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-23 20:55:17.290192: W tensorflow/core/common_runtime/pluggable_device/pluggable_device_bfc_allocator.cc:28] Overriding allow_growth setting because force_memory_growth was requested by the device.
2022-06-23 20:55:17.290639: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/device:GPU:0 with 14910 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)
2022-06-23 20:55:17.292723: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-23 20:55:17.292817: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/device:GPU:0 with 14910 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)
2022-06-23 20:55:17.293559: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-23 20:55:17.293667: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/device:GPU:0 with 14910 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)
*  TF Version: 2.9.1
*  Platform: Windows-10-10.0.22489-SP0
*  CPU: N/A
*  CPU RAM: 32 GB
*  GPU/0: DML
*  GPU RAM: 14.6 GB
*  CUDA Version: N/A
*  CUDA Build: N/A

The benchmark is running...
The tests might take up to 20 minutes
Please don't interrupt the script

1/19. MobileNet-V2

2022-06-23 20:55:24.203219: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-23 20:55:24.203491: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14910 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)
2022-06-23 20:55:24.537069: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-06-23 20:55:24.561797: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
Traceback (most recent call last):
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1377, in _do_call
    return fn(*args)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: AssignRefVariable is not yet supported for pluggable devices in this version of TensorFlow.
         [[{{node MobilenetV2/expanded_conv_1/project/BatchNorm/beta/Assign}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\__init__.py", line 63, in run
    return run_tests(training=True, inference=True, micro=False, verbose=self.verbose,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\utils.py", line 560, in run_tests
    tf.compat.v1.global_variables_initializer().run()
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\ops.py", line 2731, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\ops.py", line 5782, in _run_using_default_session
    session.run(operation, feed_dict)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1396, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'MobilenetV2/expanded_conv_1/project/BatchNorm/beta/Assign' defined at (most recent call last):
    File "<stdin>", line 1, in <module>
    File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\__init__.py", line 63, in run
      return run_tests(training=True, inference=True, micro=False, verbose=self.verbose,
    File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\utils.py", line 557, in run_tests
      input_, output_, train_vars_ = getModelSrc(test, testInfo, sess)
    File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\utils.py", line 238, in getModelSrc
      tf.compat.v1.train.import_meta_graph(test.model_src, clear_devices=True)
Node: 'MobilenetV2/expanded_conv_1/project/BatchNorm/beta/Assign'
AssignRefVariable is not yet supported for pluggable devices in this version of TensorFlow.
         [[{{node MobilenetV2/expanded_conv_1/project/BatchNorm/beta/Assign}}]]

Original stack trace for 'MobilenetV2/expanded_conv_1/project/BatchNorm/beta/Assign':
  File "<stdin>", line 1, in <module>
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\__init__.py", line 63, in run
    return run_tests(training=True, inference=True, micro=False, verbose=self.verbose,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\utils.py", line 557, in run_tests
    input_, output_, train_vars_ = getModelSrc(test, testInfo, sess)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\utils.py", line 238, in getModelSrc
    tf.compat.v1.train.import_meta_graph(test.model_src, clear_devices=True)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\training\saver.py", line 1582, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\training\saver.py", line 1603, in _import_meta_graph_with_return_elements
    meta_graph.import_scoped_meta_graph_with_return_elements(
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 804, in import_scoped_meta_graph_with_return_elements
    imported_return_elements = importer.import_graph_def(
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\deprecation.py", line 561, in new_func
    return func(*args, **kwargs)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\importer.py", line 403, in import_graph_def
    return _import_graph_def_internal(
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\importer.py", line 516, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\importer.py", line 247, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\ops.py", line 3904, in _add_new_tf_operations
    new_ops = [
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\ops.py", line 3905, in <listcomp>
    self._create_op_from_tf_operation(c_op, compute_device=compute_devices)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\ops.py", line 3787, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\ops.py", line 2133, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

**Comment by PatriceVignola** [comment]
Hi @oscarbg,

This is a known issue with the preview wheel. Unfortunately this isn't entirely in our control since this functionality wasn't exposed for pluggable devices by TensorFlow 2.9, which is the latest version of TensorFlow available at the moment. For AI-Benchmark to work well with pluggable devices, 2 changes are needed:

https://github.com/tensorflow/tensorflow/pull/55640
https://github.com/tensorflow/tensorflow/pull/55645

[The first one](https://github.com/tensorflow/tensorflow/pull/55640) has been merged and therefore should be available as soon as TensorFlow 2.10 is released, but [the second one](https://github.com/tensorflow/tensorflow/pull/55645) hasn't been merged yet, even though it has been approved. It is unclear at this moment if it can make it into 2.10 or if we have to wait until 2.11.

We'll update this issue when we have more info!

**Comment by PatriceVignola** [comment]
Hi @oscarbg,

This is a known issue with the preview wheel. Unfortunately this isn't entirely in our control since this functionality wasn't exposed for pluggable devices by TensorFlow 2.9, which is the latest version of TensorFlow available at the moment. For AI-Benchmark to work well with pluggable devices, 2 changes are needed:

https://github.com/tensorflow/tensorflow/pull/55640
https://github.com/tensorflow/tensorflow/pull/55645

[The first one](https://github.com/tensorflow/tensorflow/pull/55640) has been merged and therefore should be available as soon as TensorFlow 2.10 is released, but [the second one](https://github.com/tensorflow/tensorflow/pull/55645) hasn't been merged yet, even though it has been approved. It is unclear at this moment if it can make it into 2.10 or if we have to wait until 2.11.

We'll update this issue when we have more info!

**Comment by oscarbg** [comment]
Hi @PatriceVignola ,
thanks for detailed information.. good to know at least the work is done and waiting for a PR to be merged..

**Comment by oscarbg** [comment]
Hi @PatriceVignola,
I have three questions, hope you can answer (I belive all have obvious answers but just to be sure..):

a) tensorflow-directml will require source code changes once (https://github.com/tensorflow/tensorflow/pull/55640
& https://github.com/tensorflow/tensorflow/pull/55645) are merged? lame question(?): I assume yes plugins don't take advantage of new features exposed to it automatically..

b)assuming no tensorflow-directml plugin source changes needed, once https://github.com/tensorflow/tensorflow/pull/55645 is merged, I can test the AI-benchmark using existing plugin on some tensorflow nightly build with this merge? I say if it's merged post 2.10 release for not waiting till 2.11 release? or using tensorflow-directml plugin depends strictly on using it on the version is built (2.9 currently)?

c) I suppose same limitation applies to other GPU accelerated tensorflow-plugin I know that is tensorflow-metal (https://pypi.org/project/tensorflow-metal)..
I can't test on it.. but I assume AI-Benchmark doesn't run correctly.. and depending on previous answers once https://github.com/tensorflow/tensorflow/pull/55645 merged I may ask also Apple developers to update Metal plugin for AssignRefVariable support, right?

thanks..

**Comment by PatriceVignola** [comment]
a) You're right that some changes made into TensorFlow Core would require us to release a new version of `tensorflow-directml-plugin`. But luckily, we anticipated both https://github.com/tensorflow/tensorflow/pull/55640 and https://github.com/tensorflow/tensorflow/pull/55645 and the code is already there to dynamically load the functions as soon as it's available!

https://github.com/microsoft/tensorflow-directml-plugin/blob/5c15a7df2b6a18bd908c60faad967af5638b83ec/tfdml/runtime_adapter/op_kernel_context.cc#L60-L63

https://github.com/microsoft/tensorflow-directml-plugin/blob/5c15a7df2b6a18bd908c60faad967af5638b83ec/tfdml/runtime_adapter/op_kernel_context.cc#L83-L84

https://github.com/microsoft/tensorflow-directml-plugin/blob/5c15a7df2b6a18bd908c60faad967af5638b83ec/tfdml/runtime_adapter/op_kernel_context.cc#L104-L105

So If everything goes well, we shouldn't need to release a new version of `tensorflow-directml-plugin` to take advantage of these changes.

b) You can already start using https://github.com/tensorflow/tensorflow/pull/55640 with the latest `tf-nightly-cpu` and the current `tensorflow-directml-plugin` packages if you don't want to wait until the TF 2.10 release (although the package may be unstable). As soon as https://github.com/tensorflow/tensorflow/pull/55645 is merged, you'll also be able to use it with `tf-nightly-cpu` within a day or two. As explained in a), we don't anticipate that a new version of `tensorflow-directml-plugin` will be necessary to take advantage of these changes.

c) AI-Benchmark may run correctly with `tensorflow-metal`, but I suspect the performance won't be great. The reason it doesn't work with our plugin is because we deliberately throw an error when users attempt to use `AssignRef`:

https://github.com/microsoft/tensorflow-directml-plugin/blob/5c15a7df2b6a18bd908c60faad967af5638b83ec/tfdml/kernels/dml_assign_variable_op.cc#L82-L87

Otherwise, performance would be abysmal and AI-Benchmark wouldn't output scores that are representative of the performance of the plugin. Therefore, my assumption is that you can run AI-Benchmark against `tensorflow-metal`, but it probably won't run with peak performance.

Let us know if you have other questions!

**Comment by oscarbg** [comment]
really thanks @PatriceVignola for your very informative response! good news plugin is ready.. think will close issue as soon remaining PR is merged and can test AI Benchmark on tf-nightly..

**Comment by oscarbg** [comment]
Hi @PatriceVignola ,
a little update tested with tf-nightly-cpu 28072022 which has finally the two PRs merged and seems aibenchmark runs great up to to test 7 VGG-16:
fails with:
`2022-07-28 19:57:12.287066: W tensorflow/c/logging.cc:37] OP_REQUIRES failed at D:\a\_work\1\s\tfdml\kernels\dml_conv_ops.cc:868 : Fusion is not implemented: [BiasAddReluf┌☻,Reluf┌☻]`

is this a known issue?

thanks..

full log:
```
7/19. VGG-16

2022-07-28 19:57:11.983011: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-28 19:57:11.983281: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6910 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)
2022-07-28 19:57:12.046440: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2022-07-28 19:57:12.239408: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2022-07-28 19:57:12.287066: W tensorflow/c/logging.cc:37] OP_REQUIRES failed at D:\a\_work\1\s\tfdml\kernels\dml_conv_ops.cc:868 : Fusion is not implemented: [BiasAddReluf┌☻,Reluf┌☻]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\__init__.py", line 63, in run
    return run_tests(training=True, inference=True, micro=False, verbose=self.verbose,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\ai_benchmark\utils.py", line 583, in run_tests
    sess.run(output_, feed_dict={input_: data})
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1371, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1378, in _do_call
    return fn(*args)
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1361, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "c:\users\rtfss\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\client\session.py", line 1454, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 40: invalid continuation byte
```

**Comment by PatriceVignola** [comment]
Hey Oscar,

Yes, we are aware of this issue. The current tensorflow-directml-plugin pypi package won't be compatible with TF 2.10, so an upgrade will be needed. We are planning to release the next version of tensorflow-directlm-plugin shortly after the release of TF 2.10.

If you don't mind building from source, you can already try it out by building from the `main` branch with `python build.py --install`.

**Comment by oscarbg** [comment]
Hey @PatriceVignola ,
yep it works!
builded as you pointed out but in release mode: python build.py -c release --install.
