### ISSUE TITLE
DML doesn't support exponential_avg_factor != 1 at the moment

### ISSUE THREAD

**Issue by Abdelrahman-7gab** [microsoft/tensorflow-directml-plugin#297]
I'm running some different codes to make comparisons between CUDA and DirectML Just to determine if Utilizing AMD GPUS for deployment in the future is going to be possible!
I know that this plugin is still under development, however after running a piece of code that works on Tensorflow-cpu and on Tensorflow using CUDA, a lot of the models seem to work flawlessly and some tend to just not.

for example I get the following error when trying out code that works on CUDA:
```
Traceback (most recent call last):
  File "d:\DCASE\Code\SELD\trainv2.py", line 380, in <module>
    main(get_param())
  File "d:\DCASE\Code\SELD\trainv2.py", line 338, in main
    train_iterloop(model, trainset, epoch, optimizer)
  File "d:\DCASE\Code\SELD\trainv2.py", line 84, in iterloop
    preds, sloss, dloss = step(model, x, y, optimizer)
  File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\tensorflow\python\eager\execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'model/batch_normalization/FusedBatchNormV3' defined at (most recent call last):
    File "d:\DCASE\Code\SELD\trainv2.py", line 380, in <module>
      main(get_param())
    File "d:\DCASE\Code\SELD\trainv2.py", line 338, in main
      train_iterloop(model, trainset, epoch, optimizer)
    File "d:\DCASE\Code\SELD\trainv2.py", line 84, in iterloop
      preds, sloss, dloss = step(model, x, y, optimizer)
    File "d:\DCASE\Code\SELD\trainv2.py", line 35, in trainstep
      y_p = model(x, training=True)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\training.py", line 557, in __call__
      return super().__call__(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\functional.py", line 510, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\functional.py", line 667, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\layers\normalization\batch_normalization.py", line 850, in call        
      outputs = self._fused_batch_norm(inputs, training=training)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\layers\normalization\batch_normalization.py", line 660, in _fused_batch_norm
      output, mean, variance = control_flow_util.smart_cond(
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\control_flow_util.py", line 108, in smart_cond
      return tf.__internal__.smart_cond.smart_cond(
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\layers\normalization\batch_normalization.py", line 634, in _fused_batch_norm_training
      return tf.compat.v1.nn.fused_batch_norm(
Node: 'model/batch_normalization/FusedBatchNormV3'
Detected at node 'model/batch_normalization/FusedBatchNormV3' defined at (most recent call last):
    File "d:\DCASE\Code\SELD\trainv2.py", line 380, in <module>
      main(get_param())
    File "d:\DCASE\Code\SELD\trainv2.py", line 338, in main
      train_iterloop(model, trainset, epoch, optimizer)
    File "d:\DCASE\Code\SELD\trainv2.py", line 84, in iterloop
      preds, sloss, dloss = step(model, x, y, optimizer)
    File "d:\DCASE\Code\SELD\trainv2.py", line 35, in trainstep
      y_p = model(x, training=True)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\training.py", line 557, in __call__
      return super().__call__(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\functional.py", line 510, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\functional.py", line 667, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\engine\base_layer.py", line 1097, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\layers\normalization\batch_normalization.py", line 850, in call        
      outputs = self._fused_batch_norm(inputs, training=training)
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\layers\normalization\batch_normalization.py", line 660, in _fused_batch_norm
      output, mean, variance = control_flow_util.smart_cond(
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\utils\control_flow_util.py", line 108, in smart_cond
      return tf.__internal__.smart_cond.smart_cond(
    File "C:\Users\okabi\anaconda3\envs\seld\lib\site-packages\keras\layers\normalization\batch_normalization.py", line 634, in _fused_batch_norm_training
      return tf.compat.v1.nn.fused_batch_norm(
Node: 'model/batch_normalization/FusedBatchNormV3'
2 root error(s) found.
  (0) INVALID_ARGUMENT:  DML doesn't support exponential_avg_factor != 1 at the moment
         [[{{node model/batch_normalization/FusedBatchNormV3}}]]
         [[model/multi_head_attention__2/einsum_2/Einsum/ReadVariableOp/_74]]
  (1) INVALID_ARGUMENT:  DML doesn't support exponential_avg_factor != 1 at the moment
         [[{{node model/batch_normalization/FusedBatchNormV3}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_trainstep_43850]

```
so is there like a timeline to when do you guys think you can get that plugin to be stable and or production ready? 
also is there a place that we can read the changelog between the different releases? 
thank you for your time and for your consideration.

**Comment by PatriceVignola** [comment]
Thank you for opening this issue! We didn't have any signal before to tell us to prioritize supporting `exponential_avg_factor` since none of the models that we track used it, but issues like that help us prioritize it. Do you have other examples of models that work on CUDA but didn't work with DML? We heavily prioritize addressing GitHub issues so we would love to hear about it.

Unfortunately we don't have a timeline yet as to when the plugin will be production ready since it's dependent on a lot of factors (e.g. TensorFlow release schedule, performance improvements), but I would say the current state of the plugin is already better than what we had with TensorFlow-DirectML 1.15.

You can read the changelogs on the [releases page](https://github.com/microsoft/tensorflow-directml-plugin/releases)!

**Comment by bobfromjapan** [comment]
I have same issue with efficientnet(v2) models implemented by TensorFlow officially.

- tf.keras.applications.efficientnet
- tf.keras.applications.efficientnet_v2

I hope you will consider supporting it! Thanks!

**Comment by aliencaocao** [comment]
Same issue here, with efficient net B3

**Comment by PatriceVignola** [comment]
Support for `exponential_avg_factor` has been [merged last week](https://github.com/microsoft/tensorflow-directml-plugin/commit/015a296bd494f8b220094060883e36580822419c), and we're currently [preparing a 0.2.0 release](https://github.com/microsoft/tensorflow-directml-plugin/commit/f075f2a95db8e4fdd1529e7ef278ece998eb9e0d) by the end of the week. As soon as our internal testing is done, we'll be able to release it.

@aliencaocao The reason it wasn't supported yet is that we have been focusing on feature parity with tensorflow-directml 1.15 so far, and `exponential_avg_factor` has only been added as part of TensorFlow 2. As soon as this issue was opened, we prioritized it in our backlog and started working on it.

**Comment by aliencaocao** [comment]
I understand, totally have no intention to blame you guys or something. Thanks for the update on the merge and 0.2.0. Looking forward to it!

**Comment by PatriceVignola** [comment]
@Abdelrahman-7ga @bobfromjapan @aliencaocao [tensorflow-directml-plugin==0.2.0](https://pypi.org/project/tensorflow-directml-plugin/0.2.0.dev221020/) has been released, which includes support for `exponential_avg_factor != 1.0`.

**Comment by aliencaocao** [comment]
It is fixed, thank you
