### ISSUE TITLE
TensorFlow 2.11.0 support?

### ISSUE THREAD

**Issue by netcorefan1** [microsoft/tensorflow-directml-plugin#352]
Hello,
I installed this plugin after realizing that TensorFlow does not support Nvidia natively anymore.
During installation I  noticed that it automatically installed `tensorflow-cpu==2.10.0` which is the latest one to support GPU and I'm wondering what could be the point when 2.10 alone already runs CUDA natively and in a production ready manner.
So, I upgraded to 2.11.0 , but when I run `import tensorflow as tf` I get the following exception:
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\__init__.py", line 440, in <module>
    _ll.load_library(_plugin_dir)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\load_library.py", line 151, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow-plugins\tfdml_plugin.dll not found
```
Is there a way to run the latest TF with GPU on Windows natively?
I must have missed something. It looks strange that such famous framework does not run in a Windows-Nvidia combo (supposed to be the most popular). 
I have the latest gen Nvidia card with the latest Cuda 12 SDK toolkit.
Thanks

**Comment by maggie1059** [comment]
Hi @netcorefan1, we skipped TF 2.11 support due to a breaking change in Keras 2.11's optimizers, so our current dependency is 2.10. However, this will be resolved with 2.12 and we will be updating to 2.12 when it's released. I'll update here when the new version of our plugin with 2.12 is released!

**Comment by netcorefan1** [comment]
This is really a great news. Hope to see it soon! Thanks
