### ISSUE TITLE
cannot import name 'ops' from 'keras' when importing keras_hub

### ISSUE THREAD

**Issue by nickums** [microsoft/tensorflow-directml-plugin#380]
I have keras 2.10.0 and now installed keras-hub 0.18.1 with no dependency conflicts.
I am on windows10 with python3.9 and have to stay with tensorflow 2.10.0
what version of keras should I have?

    import keras_hub

Traceback (most recent call last):
  File "D:/OurStuff/AI/keras/keras_inference.py", line 1, in <module>
    import keras_hub
  File "C:\Python\Python39\lib\site-packages\keras_hub\__init__.py", line 10, in <module>
    from keras_hub.api import *  # noqa: F403
  File "C:\Python\Python39\lib\site-packages\keras_hub\api\__init__.py", line 7, in <module>
    from keras_hub.api import bounding_box
  File "C:\Python\Python39\lib\site-packages\keras_hub\api\bounding_box\__init__.py", line 7, in <module>
    from keras_hub.src.bounding_box.converters import convert_format
  File "C:\Python\Python39\lib\site-packages\keras_hub\src\bounding_box\converters.py", line 4, in <module>
    from keras import ops
ImportError: cannot import name 'ops' from 'keras' (C:\Python\Python39\lib\site-packages\keras\__init__.py)

**Comment by nickums** [comment]
I am advised frpm the keras users group that this requires keras3.
 It seems that having tensorflow 2.10.0 restricts keras to 2.10 or 2.11
I;ve upgraded keras to 3.7.0 anyway to see what happens...
